version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8088:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  frontend:
    build:
      context: .  # Aquí se indica el directorio raíz del proyecto
      dockerfile: docker/Dockerfile.frontend
    container_name: vue-frontend
    working_dir: /app
    ports:
      - "8089:8089"
    volumes:
      - ./frontend:/app
    command: 
      ["npm", "run", "serve", "--", "--port", "8089", "--host", "0.0.0.0"]

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

networks:
  default:
    name: laravel-network

