# Imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias
COPY /frontend/package.json ./
COPY /frontend/package-lock.json ./


# Instala las dependencias
RUN npm install

# Copia todo el código fuente del proyecto
COPY . .

# Expone el puerto en el que corre Vue.js (por defecto, el 8080)
EXPOSE 8089

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "serve"]

